### PR TITLE
LoggedInView.java

### PR DESCRIPTION
**Pull request by kevinhu01**
Completed TODO 1: execute the logout use case through the Controller.
Completed TODO 2: save the logout controller in the instance variable.

Also some markings from README to show completion of steps.

### CODE REVIEW

**Comment by JingduoZhou** [comment]
looks good.

**Comment by BradC1** [comment]
good

**Review by BradC1 — APPROVED** [review]
good

**Review by JingduoZhou — COMMENTED** [review]
looks good.

**Comment by XYPKQ896** [comment]
Good

**Pull request merged**
